version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: property_parser_development
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-54321}
    ports:
      - '5432:5432'
    env_file: .env

  web:
    build: .
    command: bash -c "./bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - PG_USER=${PG_USER:-postgres}
      - PG_PASSWORD=${PG_PASSWORD:-54321}
      - PG_HOST=db
      - PG_PORT=${PG_PORT:-5432}
      - DOCKER=true
    env_file: .env

volumes:
  postgres_data: {}
