default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DOCKER"] == "true" ? ENV["PG_HOST"] : "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>
  username: <%= ENV["PG_USER"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "54321" %>

development:
  primary: &primary_development
    <<: *default
    database: property_parser_development
  queue:
    <<: *primary_development
    database: property_parser_development_queue
    
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: property_parser_test

production:
  primary: &primary_production
    <<: *default
    database: property_parser_production
  queue:
    <<: *primary_production
    database: property_parser_production_queue
    migrations_paths: db/queue_migrate
